--TẠO ROLE TRONG DATABASE
USE DB_QLBH;
GO
CREATE ROLE [roleTaiXe] AUTHORIZATION [dbo];

--TẠO TÀI KHOẢN TRONG DATABASE
use DB_QLBH
go
CREATE LOGIN [taixe] WITH PASSWORD=N'taixe', 
                       DEFAULT_DATABASE=[DB_QLBH], 
                       CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;

--?
go
use DB_QLBH
GO
-- Create Database Users
CREATE USER [TaiXe] FOR LOGIN [taixe] WITH DEFAULT_SCHEMA=[dbo];

--THÊM TÀI KHOẢN VÀO ROLE
go
use DB_QLBH
GO
ALTER ROLE [roleTaiXe] ADD MEMBER [taixe];

--CẤP QUYỀN
go
use DB_QLBH
GO
GRANT UPDATE (TinhTrang) on DONHANG TO TAIXE
GRANT SELECT ON DONHANG TO TAIXE
GRANT SELECT ON CTDONHANG TO TAIXE
GRANT INSERT ON TAIXE TO TAIXE
GRANT SELECT ON TAIXE TO TAIXE




-------------------
--TẠO ROLE TRONG DATABASE
USE DB_QLBH;
GO
CREATE ROLE [roleKhachHang] AUTHORIZATION [dbo];

--TẠO TÀI KHOẢN TRONG DATABASE
use DB_QLBH
go
CREATE LOGIN [khachhang] WITH PASSWORD=N'khachhang', 
                       DEFAULT_DATABASE=[DB_QLBH], 
                       CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;

--?
go
use DB_QLBH
GO
-- Create Database Users
CREATE USER [KhachHang] FOR LOGIN [khachhang] WITH DEFAULT_SCHEMA=[dbo];

--THÊM TÀI KHOẢN VÀO ROLE
go
use DB_QLBH
GO
ALTER ROLE [roleKhachHang] ADD MEMBER [KhachHang];

--CẤP QUYỀN
go
use DB_QLBH
GO
GRANT INSERT ON KHACHHANG TO KHACHHANG
GRANT SELECT ON KHACHHANG TO KHACHHANG
GRANT UPDATE ON KHACHHANG TO KHACHHANG
GRANT SELECT ON DOITAC TO KHACHHANG
GRANT SELECT ON SANPHAM TO KHACHHANG
GRANT INSERT ON CTDONHANG TO KHACHHANG
GRANT SELECT ON DONHANG TO KHACHHANG

----------------
--TẠO ROLE TRONG DATABASE
USE DB_QLBH;
GO
CREATE ROLE [roleDoiTac] AUTHORIZATION [dbo];

--TẠO TÀI KHOẢN TRONG DATABASE
use DB_QLBH
go
CREATE LOGIN [doitac] WITH PASSWORD=N'doitac', 
                       DEFAULT_DATABASE=[DB_QLBH], 
                       CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;

--?
go
use DB_QLBH
GO
-- Create Database Users
CREATE USER [DoiTac] FOR LOGIN [doitac] WITH DEFAULT_SCHEMA=[dbo];

--THÊM TÀI KHOẢN VÀO ROLE
go
use DB_QLBH
GO
ALTER ROLE [roleDoiTac] ADD MEMBER [doitac];

--CẤP QUYỀN
go
use DB_QLBH
GO
GRANT INSERT ON DOITAC TO DOITAC
GRANT SELECT ON DOITAC TO DOITAC

GRANT INSERT ON CHINHANH TO DOITAC
GRANT SELECT ON CHINHANH TO DOITAC

GRANT INSERT ON HOPDONG TO DOITAC
GRANT SELECT ON HOPDONG TO DOITAC

GRANT INSERT ON SANPHAM TO DOITAC
GRANT UPDATE ON SANPHAM TO DOITAC
GRANT DELETE ON SANPHAM TO DOITAC

GRANT SELECT ON DONHANG TO DOITAC
GRANT SELECT ON CTDONHANG TO DOITAC
GRANT UPDATE ON DONHANG TO DOITAC


------------------
--TẠO ROLE TRONG DATABASE
USE DB_QLBH;
GO
CREATE ROLE [roleNhanVien] AUTHORIZATION [dbo];

--TẠO TÀI KHOẢN TRONG DATABASE
use DB_QLBH
go
CREATE LOGIN [nhanvien] WITH PASSWORD=N'nhanvien', 
                       DEFAULT_DATABASE=[DB_QLBH], 
                       CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;

--?
go
GO
-- Create Database Users
use DB_QLBH
CREATE USER [NhanVien] FOR LOGIN [nhanvien] WITH DEFAULT_SCHEMA=[dbo];

--THÊM TÀI KHOẢN VÀO ROLE
go
use DB_QLBH
GO
ALTER ROLE [roleNhanVien] ADD MEMBER [nhanvien];

--CẤP QUYỀN
go
use DB_QLBH
GO
GRANT SELECT ON HOPDONG TO NHANVIEN





-------
--TẠO ROLE TRONG DATABASE
USE DB_QLBH;
GO
CREATE ROLE [roleAdmin] AUTHORIZATION [dbo];

--TẠO TÀI KHOẢN TRONG DATABASE
use DB_QLBH
go
CREATE LOGIN [admin] WITH PASSWORD=N'admin', 
                       DEFAULT_DATABASE=[DB_QLBH], 
                       CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;

--?
go
use DB_QLBH
GO
-- Create Database Users
CREATE USER [Admin] FOR LOGIN [admin] WITH DEFAULT_SCHEMA=[dbo];

--THÊM TÀI KHOẢN VÀO ROLE
go
use DB_QLBH
GO
ALTER ROLE [roleAdmin] ADD MEMBER [admin];

--CẤP QUYỀN
go
use DB_QLBH
GO
GRANT CONTROL TO ADMIN
